### ISSUE TITLE
PhotometricSystem = load_additional_systems fails

### ISSUE THREAD

**Issue by stephengwyn** [gaia-dpci/GaiaXPy#50]
**Describe the bug**
If I download the CFHT/MegaCam filter system XML file (http://svo2.cab.inta-csic.es/theory/fps/getgaiaxpy.php?gxpyid=CFHT/MegaCam) linked off the SVO page at: http://svo2.cab.inta-csic.es/theory/fps/index.php?id=CFHT/MegaCam.u&&mode=browse&gname=CFHT&gname2=MegaCam#filter
and put it in a directory, and then try to load that filter system using  
`PhotometricSystem = load_additional_systems('directory/name/')
`
I get a stack trace indicating something when wrong. This is following the tutorial at: https://gaia-dpci.github.io/GaiaXPy-website/tutorials/Additional%20systems%20tutorial.html

**To Reproduce**
mkdir q
wget -O q/cfht_megacam.xml 'http://svo2.cab.inta-csic.es/theory/fps/getgaiaxpy.php?gxpyid=CFHT/MegaCam'
python
from gaiaxpy import PhotometricSystem, load_additional_systems
PhotometricSystem = load_additional_systems('q/')

**Expected behavior**
not a stack trace

**Screenshots**
(not useful)

**Desktop (please complete the following information):**
Ubuntu 22
python 3.10.6
gaixpy 2.0.1

**Additional context**
The tutorial is talking about importing new photometric systems in the future, so maybe the tutorial is in error?

**Comment by druzm** [comment]
Hello,

The filters files have only recently been uploaded, and there may still be some adjustments we need to make.

There are two problems in this situation:

1. GaiaXPy expects filter files names to follow a specific pattern because the name of the system and the filter version are contained in it. You should be able to download the file with its original name to an specific folder by running: `wget --content-disposition -P q/ 'http://svo2.cab.inta-csic.es/theory/fps/getgaiaxpy.php?gxpyid=CFHT/MegaCam'`
2. In this particular case, the name of the file is malformed. The name is `CFHT.MegaCam.gaiaXPy_dr3_v1.xml`, but the expected pattern is `FilterName.gaiaXPy_dr3_version.xml`, as you can see, in this file, the name of the filter is split by a dot that shouldn't be there. If you rename the file to `CFHTMegaCam.gaiaXPy_dr3_v1.xml` you should be able to use it.

Let me know how it goes. As I said, this is recent work, and we've still got some more instructions and details to add to the tutorials. I'll get sure to report the issue with the file names.

Thank you for the report.

**Comment by stephengwyn** [comment]
OK, that worked a lot better after renaming the file from SVO.

Thank you for your prompt reply!

Stephen Gwyn


-------- Original message --------
From: Daniela Ruz-Mieres ***@***.***>
Date: 2023-02-09 5:19 p.m. (GMT-08:00)
To: gaia-dpci/GaiaXPy ***@***.***>
Cc: "Gwyn, Stephen" ***@***.***>, Author ***@***.***>
Subject: Re: [gaia-dpci/GaiaXPy] PhotometricSystem = load_additional_systems fails (Issue #50)


***Attention*** This email originated from outside of the NRC. ***Attention*** Ce courriel provient de l'ext?rieur du CNRC.

Hello,

The filters files have only recently been uploaded, and there may still be some adjustments we need to make.

There are two problems in this situation:

  1.  GaiaXPy expects filter files names to follow a specific pattern because the name of the system and the filter version are contained in it. You should be able to download the file with its original name to an specific folder by running: wget --content-disposition -P q/ 'http://svo2.cab.inta-csic.es/theory/fps/getgaiaxpy.php?gxpyid=CFHT/MegaCam'
  2.  In this particular case, the name of the file is malformed. The name is CFHT.MegaCam.gaiaXPy_dr3_v1.xml, but the expected pattern is FilterName.gaiaXPy_dr3_version.xml, as you can see, in this file, the name of the filter is split by a dot that shouldn't be there. If you rename the file to CFHTMegaCam.gaiaXPy_dr3_v1.xml you should be able to use it.

Let me know how it goes. As I said, this is recent work, and we've still got some more instructions and details to add to the tutorials. I'll get sure to report the issue with the file names.

Thank you for the report.

-
