### ISSUE TITLE
FITS/VOTable precision discrepancy

### ISSUE THREAD

**Issue by mbtaylor** [gaia-dpci/GaiaXPy#51]
If I write the same gaiaxpy output to FITS and VOTable using code like:
```
import gaiaxpy
query_input = ...
gaiaxpy.calibrate(query_input, output_file="spectra_f", output_format="fits")
gaiaxpy.calibrate(query_input, output_file="spectra_v", output_format="xml")
```
the FITS output for fluxes and errors is single precision (32-bit floating point, `TFORMn = '343E'`) but the VOTable output is double precision (64-bit floating point, `datatype='double' arraysize='343'`).  Is there a good reason for this?  If not I guess one or other should be changed, according to whether single or double precision is more appropriate for these values.

**Comment by druzm** [comment]
Hi @mbtaylor,

Thank you for this report. As the errors provided by the Archive use 32-bit floating point, I've modified the VOTable output to do the same using `datatype='float'`. This change should be included in the next release of the package.

Let me know if this resolves your issue. I won't close it until the fix is available.

**Comment by mbtaylor** [comment]
Thank you, yes that sounds like the right solution.

**Comment by druzm** [comment]
The requested changes have been incorporated into the [`dev`](https://github.com/gaia-dpci/GaiaXPy/tree/dev) branch. This issue can be considered resolved now.
